### PR TITLE
Update linthesia.desktop

### PR DESCRIPTION
**Pull request by trebmuh**
This adds:
- a comment (which is to be displayed when mouser-overing on the menu item)
- French generic name and comment

Hope that helps.

### CODE REVIEW

**Comment by trebmuh** [comment]
ping @arcusfelis

**Comment by mans17** [comment]
I'm having issues with desktop file for the automatic AppImage : it does not like the way 'we' package Icon, telling Icon size cannot be found.

I'll try to make an svg icon, maybe will it help... But if someone knows how to fix, please submit a PR :-)

**Comment by trebmuh** [comment]
@arcusfelis @Artoria2e5 @RushOnline : ping

**Comment by albfan** [comment]
This should be addressed by i18n setup: https://freedesktop.org/wiki/Howto_desktop_files/

Honestly migrate to meson will make all simpler, but source cannot contain translations directly

**Comment by trebmuh** [comment]
I don't know what you are talking about @albfan since I don't understand why you talk about meson here.
Also, I don't understand what makes this PR problematic for you at the point to not being merged in master. This PR is similar to dozens of PR I made against .desktop file to get the menu item to be translated for people with a localised GUI. That's way .desktop files work.

**Comment by albfan** [comment]
Build systems with i18n modules are able to add localized translations in built results.

As many other things, you can do manual work or automatize.

We will add your work and credit properly. Just in a mantainable way.

**Comment by albfan** [comment]
Build systems with i18n modules are able to add localized translations in built results.

As many other things, you can do manual work or automatize.

We will add your work and credit properly. Just in a mantainable way.

**Comment by trebmuh** [comment]
OK, thanks for the clarification.

**Comment by albfan** [comment]
@trebmuh you can see in https://github.com/linthesia/linthesia/pull/52 how to use po files to translate desktop files

**Comment by trebmuh** [comment]
If that works better/easier for you, all good then.
Thanks for having already translated the desktop file comment & name there.

**Pull request closed without merging**
