### PR TITLE
Fix keyboard offset for 61 keys

### PR DESCRIPTION
**Pull request by rikmg**

### CODE REVIEW

**Comment by albfan** [comment]
Probably we need some details on why this is better than the actual offset

**Comment by rikmg** [comment]
the minKey + maxKey intervals are used to determine if a note is in a playable range seem to be off by one octave in my 61 keyboard. The others are probably incorrect as well, but I have no way to confirm this.
In learning mode, this can cause linthesia to wait for notes that are unplayable in the higher range, and skip notes that are playable in the lower range.

**Comment by albfan** [comment]
makes sense that in learning mode, anything outside that range is not consider as active, so you don't miss a stroke due to unplayable notes.

but based on min,max check if note is playable, without check the current octave, doesn't make sense, as you can move around and the min and max will change.

Do you think you can work on that logic?

**Comment by albfan** [comment]
Without any other reference, your PR based on this info looks correct:

https://www.inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies

Probably a GUI to configure piano layouts would make sense but that would by a different PR

**Comment by rikmg** [comment]
> but based on min,max check if note is playable, without check the current octave, doesn't make sense, as you can move around and the min and max will change.
> 
> Do you think you can work on that logic?

Perhaps instead of showing only the keys in the keyboard that can be played, we could always show the entire 88 keyboard, and grey out the keys that cannot be reached. We could also grey out the falling notes that aren't reachable

The learning mode would also ignore the notes that cannot be reached, and it should take into account the current octave (the `m_note_offset` variable), instead of being fixed

On another note, the logic in the `Keyboard::GetKeyboardDefaults` could be simplified, as the minkey and maxkey can be calculated from the starting octave + starting key + number of keys in the piano. Currently we appear to have a mismatched between the two, leading to issues.

> Probably a GUI to configure piano layouts would make sense but that would by a different PR

It makes sense if the piano layouts are not standardized.

**Pull request merged**
