### PR TITLE
Debian improvements

### PR DESCRIPTION
**Pull request by trebmuh**
Needed in order to be compiled under Debian Stretch.

### CODE REVIEW

**Comment by trebmuh** [comment]
ping here too @arcusfelis

**Comment by laf0rge** [comment]
ping? why is there no merge?

**Comment by trebmuh** [comment]
@arcusfelis @Artoria2e5 @RushOnline : ping here too

**Comment by Artoria2e5** [comment]
not org member, sorry :( PR looks good

**Comment by albfan** [comment]
My personal suggestion is to remove this from project and create a new repo with this debian spec files while contacting debian maintainers for linthesia package and see if really they need this or are able to maintain outside this repo (which looks the most sane movement)

**Comment by albfan** [comment]
Let's update this if a debian or ubuntu maintainer wants to use that info and get tne inertia to spin off this spec out of linthesia

**Comment by trebmuh** [comment]
@albfan : my PoV is: you're not removing the (quite old) debian/* files, while I've been improving those here. Why? It looks strange. Either you removes all because you think that maintaining this in the upstream (here) repo isn't a good solution, either you keep those in and enjoy the fact I updated those here. But keeping the old files without removing those is kind of a strange move I think.
By the way, linthesia is (as far as I know), not in the Debian repos nor in the ubuntu ones. So, not merging those changes is only complicating people's life if they want to get access to this soft on a debian based system.

**Comment by albfan** [comment]
My view is: If you want linthesia, ./configure;make;make install is easier.

I don't think someone not able to do that is able to create a debían package.

Probably this debian files are there from @cleto, which maintains debian package previously.

If some downstream packager tries to recreate the package, that's probably a good start. When that ends into a real debían package I Will remove it

**Comment by albfan** [comment]
As an example, if buildsystem is changed to meson, I hace no idea what changes are needed in this file

**Comment by trebmuh** [comment]
Understand that, but it is **already** the case with the files in the debian/ folder.
Those files are then more outdated than the update I'm proposing here.
By the way, some debian/ files have been updated 13 days ago, which is not consistent with what you said here.

I still don't understand.

**Comment by albfan** [comment]
I think that's about a dependency that change. That's an obvious change.

You can squash and suggest atomic changes, but sent 4 commits to end commenting some lines or change http to https or documentation depedencies (i'm unsure if really needed) doesn't offers me confidence this is worth to commit.

If explanation of changes makes sense and is easy to follow I can change my mind and merge it.

**Pull request closed without merging**
