### PR TITLE
added a volume indicator to PlayingState

### PR DESCRIPTION
**Pull request by rikmg**
a volume indicator is now shown next to the speed indicator also the play_Keys graphic was replaced with a high resolution one that includes the volume keys, and that was generated from a base svg file Also adjusted the drawing to scale with the window size

### CODE REVIEW

**Comment by albfan** [comment]
This keys are not recognized in laptops without numeric pads (just my quick test)

The keys are rendered quite worse (to thin lines for arrows)

focus on volume PR and left the rework of svg for other PR to get this accepted

**Comment by rikmg** [comment]
`
  case SDLK_KP_PLUS:  state_manager->KeyPress(KeyVolumeDown); break; // [
  case SDLK_KP_MINUS: state_manager->KeyPress(KeyVolumeUp);   break; // ]
`
yes only the keypad keys are used for volume up + volume down.

i'll separate the volume and the svg rework into two different PRs

**Comment by rikmg** [comment]
removed the svg rework

**Comment by albfan** [comment]
Sorry for confusion.

I rework this on top of latest merges on main and add some protection due to double precision that ends into this:

Captura desde 2023-05-21 12-14-22

merged on 732079d, thanks!

**Pull request closed without merging**
